
# After dowlaoding and installing R with all the libraries, please install the following additional libraries:

install.packages("zip")
install.packages('tseries')
install.packages('xts')
install.packages('Quandl')
install.packages('TTR')
install.packages('car')
install.packages("forecast")
install.packages("vars")
install.packages("timsac")
install.packages("scatterplot3d")
install.packages("rgl")
install.packages("sp")
install.packages("UScensus2000tract")
install.packages("quantmod")
install.packages('qgraph')
install.packages('tm')
install.packages('wordcloud')
install.packages('financeR')
install.packages('tis')
install.packages('WDI')
install.packages('blscrapeR')
install.packages('carData')
install.packages('webshot')
install.packages('Rcmdr')
install.packages('plotly')
install.packages('rgdal')
install.packages('fAsianOptions')
install.packages('timeDate')
install.packages('base')
install.packages('combinat')
install.packages('prob')
install.packages("d3heatmap")
install.packages('visreg')
install.packages("mice")
install.packages("Amelia")
install.packages("missForest")

# Make sure all packages are up to date:
update.packages(checkBuilt = TRUE,ask=FALSE)
