ALTER TABLE hotels_boston ADD COLUMN city VARCHAR(20) DEFAULT 'Boston';
ALTER TABLE tripadvisor_boston ADD COLUMN city VARCHAR(20) DEFAULT 'Boston';
ALTER TABLE hotels_las_vegas ADD COLUMN city VARCHAR(20) DEFAULT 'Las Vegas';
ALTER TABLE tripadvisor_las_vegas ADD COLUMN city VARCHAR(20) DEFAULT 'Las Vegas';
ALTER TABLE hotels_los_angeles ADD COLUMN city VARCHAR(20) DEFAULT 'Los Angeles';
ALTER TABLE tripadvisor_los_angeles ADD COLUMN city VARCHAR(20) DEFAULT 'Los Angeles';
ALTER TABLE hotels_miami ADD COLUMN city VARCHAR(20) DEFAULT 'Miami';
ALTER TABLE tripadvisor_miami ADD COLUMN city VARCHAR(20) DEFAULT 'Miami';
ALTER TABLE hotels_new_orleans ADD COLUMN city VARCHAR(20) DEFAULT 'New Orleans';
ALTER TABLE tripadvisor_new_orleans ADD COLUMN city VARCHAR(20) DEFAULT 'New Orleans';
ALTER TABLE hotels_new_york ADD COLUMN city VARCHAR(20) DEFAULT 'New York';
ALTER TABLE tripadvisor_new_york ADD COLUMN city VARCHAR(20) DEFAULT 'New York';
ALTER TABLE hotels_philadelphia ADD COLUMN city VARCHAR(20) DEFAULT 'Philadelphia';
ALTER TABLE tripadvisor_philadelphia ADD COLUMN city VARCHAR(20) DEFAULT 'Philadelphia';
ALTER TABLE hotels_san_diego ADD COLUMN city VARCHAR(20) DEFAULT 'San Diego';
ALTER TABLE tripadvisor_san_diego ADD COLUMN city VARCHAR(20) DEFAULT 'San Diego';
ALTER TABLE hotels_seattle ADD COLUMN city VARCHAR(20) DEFAULT 'Seattle';
ALTER TABLE tripadvisor_seattle ADD COLUMN city VARCHAR(20) DEFAULT 'Seattle';
ALTER TABLE hotels_washington_dc ADD COLUMN city VARCHAR(20) DEFAULT 'Washington DC';
ALTER TABLE tripadvisor_washington_dc ADD COLUMN city VARCHAR(20) DEFAULT 'Washington DC';
